<?php
// $Id$

function chain_menu_access_chain(&$item, $new_access_callback, $new_access_arguments) {
  // This works 99.5% of cases. Default tabs probably break but no one goes to 
  // those paths anyways.
  $item += array('access callback' => 'user_access', 'access_arguments' => array());
  array_unshift($item['access arguments'], $new_access_callback, $new_access_arguments, $item['access callback']);
  $item['access callback'] = 'chain_menu_access_callback';
}

function chain_menu_access_callback() {
  $args = func_get_args();
  $access_callback = array_shift($args);
  $access_arguments = array_shift($args);
  $old_access_callback = array_shift($args);
  if (!call_user_func_array($access_callback, $access_arguments)) {
    return FALSE;
  }
  if (is_numeric($old_access_callback)) {
    return (bool) $old_access_callback;
  }
  if (function_exists($old_access_callback)) {
    return call_user_func_array($old_access_callback, $args);
  }
}

